services:
  rm-shop:
    build: .
    container_name: rm-shop
    hostname: rm-shop
    env_file:
      - .env
    ports:
      - '127.0.0.1:8777:8777'
    networks:
      - remnawave-network
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./locales:/app/locales
    restart: unless-stopped
    depends_on:
      - rm-shop-db
  rm-shop-db:
    image: postgres:17
    container_name: rm-shop-db
    hostname: rm-shop-db
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - rm-shop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
networks:
  remnawave-network: null
volumes:
  rm-shop-db-data:
    name: rm-shop-db-data
